stages:
  - dev
deploy:dev:
  stage: dev
  tags:
    - gcp
  script:
    - echo "Deployment on Server."
    - Path=$(pwd)
    - cd /home/ubuntu/script && ./env_script.sh dev implementation-layer-nest-backend-dev $VAULT_TOKEN && cd $Path
    - mv /home/ubuntu/script/.env $Path
    - |
      sshpass -p $Xplor_Password ssh $Xplor_Username@$Xplor_IP "
        if [[ -d implementation-layer-nest-backend ]]; then
          cd /home/ubuntu/implementation-layer-nest-backend
          docker-compose down
          cd && sudo rm -rf implementation-layer-nest-backend
        fi "
    - sshpass -p $Xplor_Password ssh $Xplor_Username@$Xplor_IP  "git clone -b develop https://user:'$GITLAB_ACCESS_TOKEN'@gitlab.thewitslab.com/wil-workspace/xplor/implementation-layer-nest-backend.git "
    - sshpass -p $Xplor_Password scp .env $Xplor_Username@$Xplor_IP:/home/ubuntu/implementation-layer-nest-backend
    - sshpass -p $Xplor_Password ssh -tt $Xplor_Username@$Xplor_IP  "
        cd /home/ubuntu/implementation-layer-nest-backend && docker-compose up -d --build "
    - echo "https://implementation-layer-dev.thewitslab.com"


